name: glucose_monitoring
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  fonts:
    - family: SF Pro Text
      fonts:
        - asset: fonts/SF-Pro-Text/SF-Pro-Text-Regular.otf
          weight: 400


assets:
 - assets/logo.png
